### ISSUE TITLE
problem with "predict_image_with_RF" in predictImages.py file

### ISSUE THREAD

**Issue by svicky96** [berkgulay/WeatherPredictionFromImage#30]
I am facing a trouble while using RF prediction with "predict_image_with_RF" , I couldn't understand from where the "clf" is being imported and how to import "clf" from "RF_train" .

**Comment by berkgulay** [comment]
"clf" is name of variable (as comment line suggests for convention). You should import "RandomForestClassifier" as we do using "_from sklearn.ensemble import RandomForestClassifier_" line. And then you can create your own classifier. Here "clf" means classifier and it is a random name for your classifier. You can simply change it. Important part is "RandomForestClassifier" class. You will you it for predictions.

If I had understood your question... Hope this will help
