### ISSUE TITLE
HELP ME TO RUN THIS CODE

### ISSUE THREAD

**Issue by ikbal007** [berkgulay/WeatherPredictionFromImage#34]

**Comment by ikbal007** [comment]
which is the main code. Can you help to run this code step by step

**Comment by berkgulay** [comment]
Hey,
This repo is mostly for research purposes and contains more than just one main program. So, it does not have any unique main flow (no main function). In this repo; there are various Neural Models and M.L. algorithms which have been studied during our experiments and researches on "Weather Condition Prediction from Image". Also, there is a dataset to be used for weather recognition/prediction purposes. Check it out from #29 . We merged and filtered different datasets and strived to obtain a convenient dataset with its numpy array representations (they are in repo and can be recreated using _image_to_matrix()_ function in tools.py). You can directly use scripts like _CNN_test.py_ or _RF_train.py_ for testing/trying purposes.

If you have further specific questions, I can gladly answer.

**Comment by ikbal007** [comment]
Sir when I run the code CNN_test.py I error FileNotfoundError

"
Using TensorFlow backend.
Traceback (most recent call last):
  File "G:\WeatherPredictionFromImage-development\WeatherPredictionFromImage-development\CNN_test.py", line 9, in <module>
    validation_data = np.load("../concat100/validation_data.npy")
  File "C:\Users\IQ\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../concat100/validation_data.npy'
"

![desktop](https://user-images.githubusercontent.com/43877610/55571503-7d716500-56ba-11e9-97b1-b360c5e74418.JPG).
From where I can get this files
"
validation_data = np.load("../concat100/validation_data.npy")
validation_label = np.load("../concat100/validation_label.npy")
"

**Comment by sametkalkan** [comment]
Hi ikbal007,
Thank you for your inquiry.

We did not add numpy dataset. Instead, we added the original images. Unfortunately, it has been a long time and we did not store it. If you want to convert images into .npy files, steps are basics.

1. run image_to_matrix function in the tools.py
This may take longer due to the abundance of images(70k)
2. run concatenate function in the tools.py
This picks 1000 images from each class(already created in step 1). This is needed because dataset is unbalanced so we decided to pick 1000 images for each.

By the way, you can write your own code to create dataset independently to our code(seems a bit complex since we did not pay much attention to create them)

**Comment by berkgulay** [comment]
Yes, you can absolutely change the functions to satisfy your own needs by forking the project. For instance; you can change concatenate() function from tools.py to take more images (not just 1k), if it will be more convenient for your use case.

**Comment by berkgulay** [comment]
Yes, absolutely! Especially; you can customize step-2 above by changing concat() function, if it will be more convenient for your use case.

**Comment by HostGuest** [comment]
hi , what does it mean train_lable , i don't understand

**Comment by MedNaassi** [comment]
> Sir when I run the code CNN_test.py I error FileNotfoundError
> 
> "
> Using TensorFlow backend.
> Traceback (most recent call last):
> File "G:\WeatherPredictionFromImage-development\WeatherPredictionFromImage-development\CNN_test.py", line 9, in
> validation_data = np.load("../concat100/validation_data.npy")
> File "C:\Users\IQ\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 415, in load
> fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '../concat100/validation_data.npy'
> "
> 
> ![desktop](https://user-images.githubusercontent.com/43877610/55571503-7d716500-56ba-11e9-97b1-b360c5e74418.JPG).
> From where I can get this files
> "
> validation_data = np.load("../concat100/validation_data.npy")
> validation_label = np.load("../concat100/validation_label.npy")
> "

does the code run for you ,, 
?
