### ISSUE TITLE
Can anyone upload .npy files?

### ISSUE THREAD

**Issue by monjurulkarim** [berkgulay/WeatherPredictionFromImage#35]
Hi Guyz,
Can anyone please upload the .npy files? Because, I don't want to run 'image_to_matrix' function to such a large dataset. I'd really appreciate if someone could share their npy files.

**Comment by berkgulay** [comment]
Unfortunately, I and @sametkalkan don't have .npy files on hand. But maybe others, who already tried our project, want to help you regarding this issue. So, I am just leaving this open for a while.. 

Good Luck

**Comment by berkgulay** [comment]
Hey @monjurulkarim,
Could you get .npy files somehow?

**Comment by monjurulkarim** [comment]
@berkgulay, unfortunately, I didn't.

**Comment by berkgulay** [comment]
I am closing this issue due to timeout
