### ISSUE TITLE
Request *.npy files

### ISSUE THREAD

**Issue by chitgyi** [berkgulay/WeatherPredictionFromImage#36]
Hello, can you give me "features/features.npy" and "features/labels.npy" due to training time is so long. Please :(

**Comment by berkgulay** [comment]
Hey @chitgyi ,
Unfortunately we did not store a stable numpy file of features. But there were also other issues, which had been opened by other developers, related to this. You can find those issues (among closed ones) and ask the issuer, if they still keep the numpy file of features&labels.

**Comment by chitgyi** [comment]
@berkgulay,
Ok sir
