### ISSUE TITLE
Dataset download link error

### ISSUE THREAD

**Issue by b0unc3** [berkgulay/WeatherPredictionFromImage#37]
Hello,

I'm unable to download the dataset from the links you provide.
It says that the file train(class-0).zip has been moved.
The only link that work is the one for the class 1.

Thanks.

**Comment by berkgulay** [comment]
Hi, should be fixed now!

**Comment by Summer72Wang** [comment]
No, it is not fixed.

**Comment by berkgulay** [comment]
Hi,
I noticed that there is an issue **for class-1 only** due to the missing resource. I believe one of the team members removed the resource from his drive account. I will try to fix it.

**Comment by berkgulay** [comment]
Unfortunately, 'Class 1' of the dataset is missing, since its resources got irrevocably removed from the drive by a colleague. Closing this issue. I updated the project's README respectively.
